USE `test`;

DROP TABLE `usuarios`;

CREATE TABLE `usuarios` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `nombre` VARCHAR(255) DEFAULT NULL,
  `pais` VARCHAR(100) DEFAULT NULL
);

INSERT INTO `usuarios` (`nombre`,`pais`) VALUES ("Genevieve, Charlotte, Iris, Odessa","Virgin Islands, United States"),("Fitzgerald, Lana, Hasad, Aidan","Germany"),("Michael, Minerva, Jane, Ignacia","Montserrat"),("Mechelle, Peter, Paki, Cadman","Peru"),("Dorian, Lisandra, Lucas, Jorden","Comoros"),("Shelly, Willow, Abigail, Blair","Guadeloupe"),("Ignacia, Axel, Justine, Bree","Brazil"),("Roanna, Winifred, Dahlia, Roary","Korea, North"),("Lilah, Phoebe, Brianna, Hakeem","Martinique"),("Dane, Denton, Gil, Cameron","South Sudan");
INSERT INTO `usuarios` (`nombre`,`pais`) VALUES ("Charity, Gabriel, Armando, Brock","Falkland Islands"),("Mollie, Vielka, Kieran, Petra","Germany"),("Brielle, Julian, Kelly, Valentine","Saint Vincent and The Grenadines"),("Emmanuel, Deacon, Allegra, Kirk","Monaco"),("Armando, Quinn, Shana, Reece","Mexico"),("Wayne, Barry, Vaughan, Justina","New Zealand"),("Amena, Theodore, Lacota, Hunter","Gambia"),("Nolan, Haviva, Jordan, Barclay","Cayman Islands"),("Maggy, Naida, Lois, Denton","Netherlands"),("Brielle, Grant, Xyla, Orla","Suriname");
INSERT INTO `usuarios` (`nombre`,`pais`) VALUES ("Ignacia, Illana, Inez, Berk","Angola"),("Kaye, Lael, Gareth, Bianca","Czech Republic"),("Chase, Demetria, Kaitlin, Medge","Korea, North"),("Blaze, Palmer, Oren, Macy","Falkland Islands"),("Fulton, Shad, Logan, Magee","Paraguay"),("Karly, Andrew, Drew, Duncan","Guatemala"),("Vernon, Indira, Lani, Keane","Burundi"),("David, Carson, Daquan, Berk","Belize"),("Phyllis, Lee, Freya, Libby","Macao"),("Hilda, Leo, Stone, Savannah","French Southern Territories");
INSERT INTO `usuarios` (`nombre`,`pais`) VALUES ("Caesar, Rhea, Dahlia, Zephania","Macao"),("Candace, Forrest, Ursula, Martin","Niue"),("Berk, Vivien, Kelly, Meredith","Western Sahara"),("Oren, Teegan, Kendall, Quinn","Gibraltar"),("Thaddeus, Indigo, Isaac, Piper","Bermuda"),("Kylie, Delilah, Alexandra, Nichole","Macao"),("Flavia, Erich, Dalton, Keegan","Taiwan"),("Jaden, Jermaine, Sharon, Gay","Senegal"),("Jerry, Cameran, Mark, Ignatius","French Guiana"),("Charity, Yolanda, Arthur, Ciaran","Burundi");
INSERT INTO `usuarios` (`nombre`,`pais`) VALUES ("Sloane, Gil, Winifred, Callum","Burundi"),("Iris, Sierra, Uma, Slade","Guam"),("Kitra, Ahmed, Nita, Willow","Seychelles"),("Donna, Colleen, Kuame, Daria","Saint Vincent and The Grenadines"),("Vivien, Richard, Rina, Howard","Greenland"),("Alexander, Nasim, Nicole, Ciaran","Sri Lanka"),("Jack, Ciara, Edward, Axel","Namibia"),("Samson, Lenore, Tanek, Colorado","Argentina"),("Ferdinand, Jarrod, Drew, Dakota","New Zealand"),("Brielle, Tate, Shad, Irma","Chad");
INSERT INTO `usuarios` (`nombre`,`pais`) VALUES ("Wendy, Talon, Zahir, Jack","Tunisia"),("Forrest, Lewis, Sara, Zachery","Costa Rica"),("Joshua, Aaron, Audra, Benedict","Lithuania"),("Wayne, Dara, Oren, Dennis","Dominica"),("Mira, Ainsley, Rashad, Arsenio","Hong Kong"),("Judith, Larissa, Quail, Idola","Saint Helena, Ascension and Tristan da Cunha"),("Penelope, Branden, Callum, Lucian","Finland"),("Sydney, Mari, Hedda, Victor","Isle of Man"),("Gavin, Darrel, Ali, Jade","Namibia"),("Nash, Scarlet, Lunea, Bianca","Bahamas");
INSERT INTO `usuarios` (`nombre`,`pais`) VALUES ("Howard, Clare, Dai, Fletcher","Barbados"),("Tiger, Karen, Hall, Bianca","Reunion"),("Brenden, Griffith, Pandora, Jermaine","French Guiana"),("Tiger, Robin, Neve, Cassady","Nepal"),("William, Sonia, Maryam, Xavier","British Indian Ocean Territory"),("Jameson, Jordan, Erich, Keegan","Bhutan"),("Amethyst, Amethyst, Allegra, Coby","Guatemala"),("Olivia, Xander, Lael, Cadman","Jordan"),("Zoe, Tobias, Kibo, Elijah","Monaco"),("Jasmine, Phoebe, Hakeem, Moana","Guyana");
INSERT INTO `usuarios` (`nombre`,`pais`) VALUES ("Chancellor, Harrison, Xavier, Ori","Tajikistan"),("Zeph, Ciara, Paul, Ira","Barbados"),("Ira, Finn, Bert, Dara","Korea, North"),("Althea, Bryar, Devin, Rhonda","Dominican Republic"),("Chava, Armand, Tatyana, Theodore","Pakistan"),("Genevieve, Whilemina, Kaye, Ronan","Croatia"),("Matthew, Lareina, Robin, Jamalia","Greece"),("Tallulah, Sebastian, Dennis, Wing","Guadeloupe"),("Leilani, Remedios, Miranda, Uriah","New Zealand"),("Bianca, Colby, Lucy, Magee","Saint Vincent and The Grenadines");
INSERT INTO `usuarios` (`nombre`,`pais`) VALUES ("Jacqueline, MacKensie, Amity, Portia","Costa Rica"),("Jayme, Adam, Kendall, Zelenia","Slovakia"),("Norman, Amos, Courtney, Cameran","Brazil"),("Harriet, Lee, Shelly, Veronica","Lithuania"),("Charles, Callum, Kitra, Maite","Cuba"),("Francesca, Randall, Kasimir, Inga","Holy See (Vatican City State)"),("Hayfa, Kyra, Hadassah, Channing","Syria"),("Brock, Kessie, MacKensie, Noelani","Latvia"),("Felicia, Damon, Kenyon, Brandon","Zambia"),("Elvis, Ann, Odette, Zane","Côte D'Ivoire (Ivory Coast)");
INSERT INTO `usuarios` (`nombre`,`pais`) VALUES ("Ursula, Chelsea, Jonah, Laith","Greenland"),("Amena, Garrison, Brennan, Tana","Bermuda"),("Lavinia, Lavinia, Philip, Alyssa","Korea, South"),("Ivory, Noelani, Cassady, Tamara","Guam"),("Imani, William, Jarrod, Tyrone","China"),("Hilary, Ruby, Michael, Lani","Kuwait"),("Tiger, Bo, Unity, Irene","Turkey"),("Noah, Cheryl, Amaya, Delilah","Pitcairn Islands"),("Yoshio, Rajah, Ashton, Stephanie","Georgia"),("Stephanie, Berk, Erin, Graiden","Virgin Islands, British");
